export interface FieldDef {
  name: string;
  type: string;
  description: string;
}

export interface ScopeDef {
  name: string;
  description: string;
}

export interface ResourceDef {
  name: string;
  command: string;
  description: string;
  fields: FieldDef[];
  scopes: ScopeDef[];
}

export const RESOURCES: ResourceDef[] = [
  {
    name: "Events",
    command: "opdt events list",
    description: "Calendar events / confirms",
    fields: [
      { name: "title", type: "string", description: "Event title" },
      { name: "start_time", type: "datetime", description: "Event start time" },
      { name: "end_time", type: "datetime", description: "Event end time" },
      { name: "start_date", type: "date", description: "Event start date" },
      { name: "end_date", type: "date", description: "Event end date" },
      { name: "door_time", type: "datetime", description: "Door open time" },
      { name: "calendar_classification", type: "string", description: "Status: confirmed, past, canceled" },
      { name: "venue_id", type: "integer", description: "Venue ID" },
      { name: "venue_ownership_id", type: "integer", description: "Venue ownership ID" },
      { name: "team_id", type: "integer", description: "Team ID" },
      { name: "is_public", type: "boolean", description: "Whether event is public" },
      { name: "published_at", type: "datetime", description: "When event was published" },
      { name: "presenter", type: "string", description: "Presenter name" },
      { name: "venue_capacity", type: "integer", description: "Venue capacity" },
      { name: "age_restriction", type: "string", description: "Age restriction" },
      { name: "ticketing_arrangement", type: "string", description: "Ticketing arrangement type" },
      { name: "venue_permalink", type: "string", description: "Venue permalink slug" },
      { name: "type", type: "string", description: "Event type" },
      { name: "position", type: "integer", description: "Display position" },
      { name: "eventbrite_event_id", type: "integer", description: "Eventbrite event ID (if imported)" },
      { name: "pipeline_id", type: "integer", description: "Pipeline ID" },
      { name: "seating_chart_id", type: "integer", description: "Seating chart ID" },
      { name: "ticket_forecast", type: "integer", description: "Ticket forecast number" },
      { name: "auto_added", type: "boolean", description: "Whether auto-added" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
      { name: "updated_at", type: "datetime", description: "Record updated timestamp" },
    ],
    scopes: [
      { name: "no_occurred_pipeline_event", description: "Events without an occurred pipeline event" },
      { name: "from_eventbrite", description: "Events imported from Eventbrite" },
      { name: "not_from_eventbrite", description: "Events not from Eventbrite" },
      { name: "from_axs", description: "Events imported from AXS" },
      { name: "not_from_axs", description: "Events not from AXS" },
      { name: "upcoming_non_seated", description: "Upcoming non-seated events" },
    ],
  },
  {
    name: "Artists",
    command: "opdt artists list",
    description: "Artist records",
    fields: [
      { name: "name", type: "string", description: "Artist name" },
      { name: "hidden", type: "boolean", description: "Whether hidden" },
      { name: "on_tour", type: "boolean", description: "Whether currently on tour" },
      { name: "multi_artist", type: "boolean", description: "Whether multi-artist" },
      { name: "spotify_id", type: "string", description: "Spotify artist ID" },
      { name: "permalink", type: "string", description: "Artist permalink" },
      { name: "genres", type: "text", description: "Genres" },
      { name: "tags", type: "text", description: "Tags" },
      { name: "facebook_url", type: "string", description: "Facebook URL" },
      { name: "instagram_url", type: "string", description: "Instagram URL" },
      { name: "twitter_url", type: "string", description: "Twitter URL" },
      { name: "spotify_url", type: "string", description: "Spotify URL" },
      { name: "youtube_url", type: "string", description: "YouTube URL" },
      { name: "website_url", type: "string", description: "Website URL" },
      { name: "average_ticket_cost", type: "integer", description: "Average ticket cost" },
      { name: "total_capacity_sold", type: "float", description: "Total capacity sold" },
      { name: "last_show_date", type: "date", description: "Last show date" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
      { name: "updated_at", type: "datetime", description: "Record updated timestamp" },
    ],
    scopes: [
      { name: "displayable", description: "Non-hidden artists" },
      { name: "single_artist", description: "Single artists only" },
      { name: "multi_artist", description: "Multi-artist entries only" },
      { name: "not_analyzed", description: "Not yet analyzed" },
    ],
  },
  {
    name: "Venues",
    command: "opdt venues list",
    description: "Venue ownerships",
    fields: [
      { name: "nickname", type: "string", description: "Venue display name" },
      { name: "email", type: "string", description: "Venue email" },
      { name: "team_id", type: "integer", description: "Team ID" },
      { name: "bio", type: "text", description: "Venue bio/description" },
      { name: "primary_color_hex", type: "string", description: "Primary brand color" },
      { name: "statement_descriptor_suffix", type: "string", description: "Statement descriptor" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
      { name: "updated_at", type: "datetime", description: "Record updated timestamp" },
    ],
    scopes: [],
  },
  {
    name: "Rooms",
    command: "opdt rooms list",
    description: "Venue rooms/stages",
    fields: [
      { name: "name", type: "string", description: "Room name" },
      { name: "venue_ownership_id", type: "integer", description: "Venue ownership ID" },
      { name: "capacity", type: "integer", description: "Room capacity" },
      { name: "stage_type", type: "string", description: "Stage type" },
      { name: "calendar_color_hex", type: "string", description: "Calendar color" },
      { name: "notes", type: "text", description: "Notes" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
      { name: "updated_at", type: "datetime", description: "Record updated timestamp" },
    ],
    scopes: [],
  },
  {
    name: "Tickets",
    command: "opdt tickets list --event <id>",
    description: "Event tickets",
    fields: [
      { name: "first_name", type: "string", description: "Attendee first name" },
      { name: "last_name", type: "string", description: "Attendee last name" },
      { name: "email", type: "string", description: "Attendee email" },
      { name: "barcode", type: "string", description: "Ticket barcode" },
      { name: "checked_in_at", type: "datetime", description: "Check-in timestamp (null = not checked in)" },
      { name: "paid", type: "boolean", description: "Whether ticket is paid" },
      { name: "type", type: "string", description: "Ticket type class (Tickets::Admission, Tickets::AddOn, Tickets::Abstract)" },
      { name: "price", type: "decimal", description: "Original price" },
      { name: "discounted_price", type: "decimal", description: "Price after discount" },
      { name: "face_value", type: "decimal", description: "Face value" },
      { name: "fees", type: "decimal", description: "Total fees" },
      { name: "final_cost", type: "decimal", description: "Final cost to buyer" },
      { name: "discount", type: "decimal", description: "Discount amount" },
      { name: "refunded_at", type: "datetime", description: "Refund timestamp" },
      { name: "disputed_at", type: "datetime", description: "Dispute timestamp" },
      { name: "seat_assignment", type: "string", description: "Seat assignment" },
      { name: "seat_type", type: "string", description: "Seat type" },
      { name: "fan_id", type: "integer", description: "Fan ID" },
      { name: "promo_code_id", type: "integer", description: "Promo code ID" },
      { name: "product_name", type: "string", description: "Product name" },
      { name: "sequence_number", type: "integer", description: "Sequence number" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
      { name: "updated_at", type: "datetime", description: "Record updated timestamp" },
    ],
    scopes: [
      { name: "is_paid", description: "Paid tickets only" },
      { name: "initially_paid", description: "Tickets that were initially paid" },
      { name: "unclaimed", description: "Unclaimed tickets" },
      { name: "manifested", description: "Manifested tickets" },
      { name: "comped", description: "Complimentary tickets" },
      { name: "checked_in", description: "Checked-in tickets" },
      { name: "is_admission", description: "Admission tickets only" },
      { name: "is_add_on", description: "Add-on tickets only" },
      { name: "is_abstract", description: "Abstract tickets only" },
    ],
  },
  {
    name: "Ticket Types",
    command: "opdt ticket-types list --event <id>",
    description: "Ticket type definitions",
    fields: [
      { name: "name", type: "string", description: "Ticket type name" },
      { name: "price", type: "decimal", description: "Price" },
      { name: "available", type: "integer", description: "Number available" },
      { name: "free", type: "boolean", description: "Whether free" },
      { name: "visibility", type: "string", description: "Visibility setting" },
      { name: "sales_channel", type: "string", description: "Sales channel" },
      { name: "manifested", type: "boolean", description: "Whether manifested" },
      { name: "type", type: "string", description: "Type class" },
      { name: "position", type: "integer", description: "Display position" },
      { name: "start_time", type: "datetime", description: "Sales start time" },
      { name: "end_time", type: "datetime", description: "Sales end time" },
      { name: "start_date", type: "date", description: "Sales start date" },
      { name: "end_date", type: "date", description: "Sales end date" },
      { name: "minimum_tickets_per_order", type: "integer", description: "Minimum per order" },
      { name: "maximum_tickets_per_order", type: "integer", description: "Maximum per order" },
      { name: "absorb_fees", type: "boolean", description: "Whether fees are absorbed" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
      { name: "updated_at", type: "datetime", description: "Record updated timestamp" },
    ],
    scopes: [
      { name: "manifested", description: "Manifested ticket types" },
      { name: "unmanifested", description: "Unmanifested ticket types" },
      { name: "general_admission", description: "General admission types" },
      { name: "online_sales_channel", description: "Online sales channel only" },
      { name: "distribution_eligible", description: "Distribution eligible types" },
    ],
  },
  {
    name: "Orders",
    command: "opdt orders list --event <id>",
    description: "Ticket orders",
    fields: [
      { name: "first_name", type: "string", description: "Buyer first name" },
      { name: "last_name", type: "string", description: "Buyer last name" },
      { name: "email", type: "string", description: "Buyer email" },
      { name: "total", type: "decimal", description: "Order total" },
      { name: "subtotal", type: "decimal", description: "Subtotal before fees" },
      { name: "discount", type: "decimal", description: "Discount amount" },
      { name: "fees", type: "decimal", description: "Fee amount" },
      { name: "state", type: "string", description: "Order state (e.g. paid)" },
      { name: "cash", type: "boolean", description: "Whether cash payment" },
      { name: "complimentary", type: "boolean", description: "Whether complimentary" },
      { name: "type", type: "string", description: "Order type class" },
      { name: "token", type: "string", description: "Order token" },
      { name: "postal_code", type: "string", description: "Buyer postal code" },
      { name: "card_brand", type: "string", description: "Card brand" },
      { name: "card_last4", type: "string", description: "Last 4 digits of card" },
      { name: "manual", type: "boolean", description: "Whether manual order" },
      { name: "manual_type", type: "string", description: "Manual order type" },
      { name: "promo_code_id", type: "integer", description: "Promo code ID" },
      { name: "fan_id", type: "integer", description: "Fan ID" },
      { name: "geo_state", type: "string", description: "Geo state" },
      { name: "geo_city", type: "string", description: "Geo city" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
      { name: "updated_at", type: "datetime", description: "Record updated timestamp" },
    ],
    scopes: [
      { name: "is_paid", description: "Paid orders (default)" },
      { name: "eligible_for_refund", description: "Orders eligible for refund" },
      { name: "attended", description: "Orders with checked-in tickets" },
    ],
  },
  {
    name: "Add-Ons",
    command: "opdt add-ons list --event <id>",
    description: "Event add-ons",
    fields: [
      { name: "name", type: "string", description: "Add-on name" },
      { name: "price", type: "decimal", description: "Price" },
      { name: "available", type: "integer", description: "Number available" },
      { name: "position", type: "integer", description: "Display position" },
      { name: "start_time", type: "datetime", description: "Sales start time" },
      { name: "end_time", type: "datetime", description: "Sales end time" },
      { name: "require_ticket_type", type: "boolean", description: "Requires a ticket type" },
      { name: "absorb_fees", type: "boolean", description: "Whether fees absorbed" },
      { name: "timed_entry", type: "boolean", description: "Whether timed entry" },
      { name: "dynamic_pricing_enabled", type: "boolean", description: "Dynamic pricing enabled" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
      { name: "updated_at", type: "datetime", description: "Record updated timestamp" },
    ],
    scopes: [],
  },
  {
    name: "Promo Codes",
    command: "opdt promo-codes list --event <id>",
    description: "Event promo codes",
    fields: [
      { name: "name", type: "string", description: "Promo code name" },
      { name: "amount", type: "decimal", description: "Discount amount" },
      { name: "percentage", type: "integer", description: "Discount percentage" },
      { name: "unlimited", type: "boolean", description: "Whether unlimited uses" },
      { name: "limit", type: "integer", description: "Usage limit" },
      { name: "availability", type: "string", description: "Availability setting" },
      { name: "reveal_hidden_tickets", type: "boolean", description: "Whether reveals hidden tickets" },
      { name: "applies_to_ticket_types", type: "boolean", description: "Applies to ticket types" },
      { name: "applies_to_add_ons", type: "boolean", description: "Applies to add-ons" },
      { name: "start_time", type: "datetime", description: "Valid from" },
      { name: "end_time", type: "datetime", description: "Valid until" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
      { name: "updated_at", type: "datetime", description: "Record updated timestamp" },
    ],
    scopes: [],
  },
  {
    name: "Custom Charges",
    command: "opdt custom-charges list --event <id>",
    description: "Custom charge types",
    fields: [
      { name: "name", type: "string", description: "Charge name" },
      { name: "type", type: "string", description: "Charge type" },
      { name: "input_type", type: "string", description: "Input type" },
      { name: "enabled", type: "boolean", description: "Whether enabled" },
      { name: "sales_channel", type: "string", description: "Sales channel" },
      { name: "default_amount", type: "decimal", description: "Default amount" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
    ],
    scopes: [
      { name: "enabled", description: "Enabled charges only" },
    ],
  },
  {
    name: "Fans",
    command: "opdt fans list",
    description: "Fan profiles",
    fields: [
      { name: "first_name", type: "string", description: "First name" },
      { name: "last_name", type: "string", description: "Last name" },
      { name: "email", type: "string", description: "Email" },
      { name: "phone_number", type: "string", description: "Phone number" },
      { name: "source", type: "string", description: "Acquisition source" },
      { name: "city", type: "string", description: "City" },
      { name: "state", type: "string", description: "State" },
      { name: "zip", type: "string", description: "ZIP code" },
      { name: "company_name", type: "string", description: "Company name" },
      { name: "contact_type", type: "string", description: "Contact type" },
      { name: "lifetime_value", type: "float", description: "Lifetime value" },
      { name: "calendar_events_count", type: "integer", description: "Number of events attended" },
      { name: "birthday", type: "date", description: "Birthday" },
      { name: "facebook_url", type: "string", description: "Facebook URL" },
      { name: "instagram_url", type: "string", description: "Instagram URL" },
      { name: "twitter_url", type: "string", description: "Twitter URL" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
      { name: "updated_at", type: "datetime", description: "Record updated timestamp" },
    ],
    scopes: [
      { name: "name_or_email_like", description: "Search name or email (pass query as value)" },
      { name: "email_marketing_subscribed", description: "Subscribed to email marketing (pass venue_ownership_id as value)" },
      { name: "sms_marketing_subscribed", description: "Subscribed to SMS marketing (pass venue_ownership_id as value)" },
    ],
  },
  {
    name: "Memberships",
    command: "opdt memberships list",
    description: "Fan memberships",
    fields: [
      { name: "first_name", type: "string", description: "First name" },
      { name: "last_name", type: "string", description: "Last name" },
      { name: "email", type: "string", description: "Email" },
      { name: "status", type: "string", description: "Membership status" },
      { name: "interval", type: "string", description: "Billing interval" },
      { name: "amount_cents", type: "integer", description: "Amount in cents" },
      { name: "token", type: "string", description: "Membership token" },
      { name: "canceled_at", type: "datetime", description: "Cancellation timestamp" },
      { name: "ended_at", type: "datetime", description: "End timestamp" },
      { name: "current_period_start", type: "datetime", description: "Current period start" },
      { name: "current_period_end", type: "datetime", description: "Current period end" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
      { name: "updated_at", type: "datetime", description: "Record updated timestamp" },
    ],
    scopes: [
      { name: "active_or_trialing", description: "Active or trialing memberships" },
      { name: "not_canceled", description: "Non-canceled memberships" },
    ],
  },
  {
    name: "Finance Items",
    command: "opdt finance-items list --event <id>",
    description: "Financial line items",
    fields: [
      { name: "activity", type: "string", description: "Activity description" },
      { name: "amount", type: "decimal", description: "Amount" },
      { name: "expense_type", type: "string", description: "Expense type" },
      { name: "payment_method", type: "string", description: "Payment method" },
      { name: "is_income", type: "boolean", description: "Whether income (vs expense)" },
      { name: "paid", type: "boolean", description: "Whether paid" },
      { name: "on_settlement", type: "boolean", description: "Whether on settlement" },
      { name: "due_on", type: "date", description: "Due date" },
      { name: "issued_on", type: "date", description: "Issue date" },
      { name: "type", type: "string", description: "Finance item type" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
      { name: "updated_at", type: "datetime", description: "Record updated timestamp" },
    ],
    scopes: [],
  },
  {
    name: "Finance Categories",
    command: "opdt finance-categories list",
    description: "Finance category definitions",
    fields: [
      { name: "name", type: "string", description: "Category name" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
      { name: "updated_at", type: "datetime", description: "Record updated timestamp" },
    ],
    scopes: [],
  },
  {
    name: "Refunds",
    command: "opdt refunds list --event <id>",
    description: "Order refunds",
    fields: [
      { name: "reason", type: "string", description: "Refund reason" },
      { name: "amount", type: "decimal", description: "Refund amount" },
      { name: "max_amount", type: "decimal", description: "Maximum refund amount" },
      { name: "state", type: "string", description: "Refund state" },
      { name: "type", type: "string", description: "Refund type" },
      { name: "confirmed_at", type: "datetime", description: "Confirmation timestamp" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
      { name: "updated_at", type: "datetime", description: "Record updated timestamp" },
    ],
    scopes: [
      { name: "not_reviewing", description: "Refunds not in reviewing state (default)" },
    ],
  },
  {
    name: "Fee Rules",
    command: "opdt fee-rules list",
    description: "Fee rule definitions",
    fields: [
      { name: "minimum", type: "decimal", description: "Minimum ticket price" },
      { name: "maximum", type: "decimal", description: "Maximum ticket price" },
      { name: "opendate_service_fee", type: "decimal", description: "Opendate service fee" },
      { name: "organizer_service_fee", type: "decimal", description: "Organizer service fee" },
      { name: "processing_fee_percentage", type: "decimal", description: "Processing fee percentage" },
      { name: "processing_fee_cash", type: "decimal", description: "Cash processing fee" },
      { name: "inclusive_processing", type: "boolean", description: "Whether inclusive processing" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
      { name: "updated_at", type: "datetime", description: "Record updated timestamp" },
    ],
    scopes: [],
  },
  {
    name: "Offers",
    command: "opdt offers list",
    description: "Artist offers/deals",
    fields: [
      { name: "event_name", type: "string", description: "Event name" },
      { name: "state", type: "string", description: "Offer state" },
      { name: "start_date", type: "date", description: "Start date" },
      { name: "start_time", type: "datetime", description: "Start time" },
      { name: "venue_id", type: "integer", description: "Venue ID" },
      { name: "dollar_amount", type: "decimal", description: "Dollar amount" },
      { name: "upside_percentage", type: "integer", description: "Upside percentage" },
      { name: "dollar_or_percentage_operator", type: "string", description: "Dollar or percentage operator" },
      { name: "agent_name", type: "string", description: "Agent name" },
      { name: "agent_email", type: "string", description: "Agent email" },
      { name: "expires_at", type: "datetime", description: "Expiration timestamp" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
      { name: "updated_at", type: "datetime", description: "Record updated timestamp" },
    ],
    scopes: [
      { name: "future", description: "Future offers" },
      { name: "expired", description: "Expired offers" },
      { name: "not_expired", description: "Non-expired offers" },
      { name: "expiring_soon", description: "Expiring soon" },
    ],
  },
  {
    name: "Tags",
    command: "opdt tags list",
    description: "Tags (use --scope to filter: Artist, Fan, Offer, CalendarEvent, Note, Deal)",
    fields: [
      { name: "name", type: "string", description: "Tag name" },
      { name: "scope", type: "string", description: "Tag scope (Artist, Fan, Offer, CalendarEvent, Note, Deal)" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
    ],
    scopes: [],
  },
  {
    name: "Tagged Items",
    command: "opdt tagged-items list",
    description: "Tag-to-resource associations (use --taggable-id and --taggable-type)",
    fields: [
      { name: "tag_id", type: "integer", description: "Tag ID" },
      { name: "taggable_type", type: "string", description: "Tagged model type" },
      { name: "taggable_id", type: "integer", description: "Tagged model ID" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
    ],
    scopes: [],
  },
  {
    name: "Notes",
    command: "opdt notes list",
    description: "Notes",
    fields: [
      { name: "title", type: "string", description: "Note title" },
      { name: "body", type: "text", description: "Note body" },
      { name: "type", type: "string", description: "Note type" },
      { name: "calendar_event_id", type: "integer", description: "Associated event ID" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
      { name: "updated_at", type: "datetime", description: "Record updated timestamp" },
    ],
    scopes: [],
  },
  {
    name: "Calendar Contacts",
    command: "opdt calendar-contacts list",
    description: "Event contact associations",
    fields: [
      { name: "calendar_event_id", type: "integer", description: "Event ID" },
      { name: "contact_id", type: "integer", description: "Contact ID" },
      { name: "send_daily_ticket_updates", type: "boolean", description: "Whether receives daily ticket updates" },
      { name: "ticket_update_frequency", type: "string", description: "Update frequency" },
    ],
    scopes: [],
  },
  {
    name: "Food & Beverage",
    command: "opdt food-and-beverage list",
    description: "Food and beverage items",
    fields: [
      { name: "menu_display_name", type: "string", description: "Menu item name" },
      { name: "category", type: "string", description: "Category" },
      { name: "amount", type: "decimal", description: "Amount" },
      { name: "tip_amount", type: "decimal", description: "Tip amount" },
      { name: "payment_type", type: "string", description: "Payment type" },
      { name: "payment_status", type: "string", description: "Payment status" },
      { name: "business_date", type: "date", description: "Business date" },
      { name: "calendar_event_id", type: "integer", description: "Event ID" },
      { name: "venue_ownership_id", type: "integer", description: "Venue ownership ID" },
      { name: "voided", type: "boolean", description: "Whether voided" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
      { name: "updated_at", type: "datetime", description: "Record updated timestamp" },
    ],
    scopes: [],
  },
  {
    name: "Manual Ticket Counts",
    command: "opdt manual-ticket-counts list",
    description: "Manual ticket count entries",
    fields: [
      { name: "name", type: "string", description: "Count name" },
      { name: "price", type: "decimal", description: "Price" },
      { name: "quantity", type: "integer", description: "Quantity" },
      { name: "available", type: "integer", description: "Available count" },
      { name: "calendar_event_id", type: "integer", description: "Event ID" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
      { name: "updated_at", type: "datetime", description: "Record updated timestamp" },
    ],
    scopes: [],
  },
  {
    name: "Show Activities",
    command: "opdt show-activities list --event <id>",
    description: "Show activity timeline entries",
    fields: [
      { name: "name", type: "string", description: "Activity name" },
      { name: "start_time", type: "datetime", description: "Start time" },
      { name: "start_date", type: "date", description: "Start date" },
      { name: "set", type: "boolean", description: "Whether set" },
      { name: "show_in_advance", type: "boolean", description: "Whether shown in advance" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
      { name: "updated_at", type: "datetime", description: "Record updated timestamp" },
    ],
    scopes: [],
  },
  {
    name: "Ticket Reservations",
    command: "opdt ticket-reservations list --event <id>",
    description: "Ticket reservations",
    fields: [
      { name: "first_name", type: "string", description: "First name" },
      { name: "last_name", type: "string", description: "Last name" },
      { name: "email", type: "string", description: "Email" },
      { name: "state", type: "string", description: "Reservation state" },
      { name: "token", type: "string", description: "Reservation token" },
      { name: "total", type: "decimal", description: "Total amount" },
      { name: "cash", type: "boolean", description: "Whether cash" },
      { name: "complimentary", type: "boolean", description: "Whether complimentary" },
      { name: "expires_at", type: "datetime", description: "Expiration time" },
      { name: "completed_at", type: "datetime", description: "Completion time" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
      { name: "updated_at", type: "datetime", description: "Record updated timestamp" },
    ],
    scopes: [],
  },
  {
    name: "Inbound Submissions",
    command: "opdt inbound-submissions create --app-id <id>",
    description: "Artist inbound submissions",
    fields: [
      { name: "artist_name", type: "string", description: "Artist name" },
      { name: "name", type: "string", description: "Submitter name" },
      { name: "email", type: "string", description: "Submitter email" },
      { name: "phone", type: "string", description: "Phone number" },
      { name: "location", type: "string", description: "Location" },
      { name: "spotify", type: "string", description: "Spotify URL" },
      { name: "instagram", type: "string", description: "Instagram URL" },
      { name: "venue_ownership_id", type: "integer", description: "Venue ownership ID" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
      { name: "updated_at", type: "datetime", description: "Record updated timestamp" },
    ],
    scopes: [],
  },
];

export const CONSUMER_RESOURCES: ResourceDef[] = [
  {
    name: "Consumer Confirms",
    command: "opdt consumer confirms list",
    description: "Events from the fan perspective (published, public events)",
    fields: [
      { name: "title", type: "string", description: "Event title" },
      { name: "start_date", type: "date", description: "Event start date" },
      { name: "start_time", type: "datetime", description: "Event start time" },
      { name: "end_date", type: "date", description: "Event end date" },
      { name: "end_time", type: "datetime", description: "Event end time" },
      { name: "door_time", type: "datetime", description: "Door open time" },
      { name: "presenter", type: "string", description: "Presenter name" },
      { name: "calendar_classification", type: "string", description: "Event status" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
    ],
    scopes: [],
  },
  {
    name: "Consumer Tickets",
    command: "opdt consumer tickets list",
    description: "Fan's purchased tickets",
    fields: [
      { name: "barcode", type: "string", description: "Ticket barcode (identifier)" },
      { name: "first_name", type: "string", description: "Attendee first name" },
      { name: "last_name", type: "string", description: "Attendee last name" },
      { name: "email", type: "string", description: "Attendee email" },
      { name: "product_name", type: "string", description: "Product/ticket type name" },
      { name: "final_cost", type: "decimal", description: "Final cost" },
      { name: "face_value", type: "decimal", description: "Face value" },
      { name: "share_code", type: "string", description: "Share code for claiming" },
      { name: "seat_assignment", type: "string", description: "Seat assignment" },
      { name: "seat_type", type: "string", description: "Seat type" },
      { name: "delivery_type", type: "string", description: "Delivery type" },
      { name: "delivery_time", type: "datetime", description: "Delivery time" },
      { name: "sequence_number", type: "integer", description: "Sequence number" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
    ],
    scopes: [],
  },
  {
    name: "Consumer Ticket Transfers",
    command: "opdt consumer ticket-transfers list",
    description: "Ticket transfers between fans",
    fields: [
      { name: "first_name", type: "string", description: "Recipient first name" },
      { name: "last_name", type: "string", description: "Recipient last name" },
      { name: "email", type: "string", description: "Recipient email" },
      { name: "note", type: "text", description: "Transfer note" },
      { name: "state", type: "string", description: "Transfer state" },
      { name: "transferred_at", type: "datetime", description: "Transfer timestamp" },
    ],
    scopes: [],
  },
  {
    name: "Consumer Memberships",
    command: "opdt consumer memberships list",
    description: "Fan's memberships",
    fields: [
      { name: "token", type: "string", description: "Membership token (identifier)" },
      { name: "status", type: "string", description: "Membership status" },
      { name: "amount_cents", type: "integer", description: "Amount in cents" },
      { name: "interval", type: "string", description: "Billing interval" },
      { name: "first_name", type: "string", description: "Member first name" },
      { name: "last_name", type: "string", description: "Member last name" },
      { name: "email", type: "string", description: "Member email" },
      { name: "current_period_start", type: "datetime", description: "Current period start" },
      { name: "current_period_end", type: "datetime", description: "Current period end" },
      { name: "canceled_at", type: "datetime", description: "Cancellation timestamp" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
    ],
    scopes: [],
  },
  {
    name: "Consumer Users",
    command: "opdt consumer users current",
    description: "Fan user account management",
    fields: [
      { name: "email", type: "string", description: "User email" },
      { name: "first_name", type: "string", description: "First name" },
      { name: "last_name", type: "string", description: "Last name" },
      { name: "time_zone", type: "string", description: "Time zone" },
    ],
    scopes: [],
  },
  {
    name: "Consumer Push Notifications",
    command: "opdt consumer push-notifications list",
    description: "Push notifications sent to the fan",
    fields: [
      { name: "message", type: "text", description: "Notification message" },
      { name: "subtitle", type: "string", description: "Notification subtitle" },
      { name: "created_at", type: "datetime", description: "Record created timestamp" },
    ],
    scopes: [],
  },
  {
    name: "Consumer Venue Ownerships",
    command: "opdt consumer venue get",
    description: "Venue/organization info from fan perspective",
    fields: [
      { name: "bio", type: "text", description: "Venue bio" },
      { name: "time_zone", type: "string", description: "Venue time zone" },
    ],
    scopes: [],
  },
];

export const RANSACK_PREDICATES = [
  { suffix: "_eq", description: "Equals", example: 'status_eq=active' },
  { suffix: "_not_eq", description: "Not equals", example: 'status_not_eq=canceled' },
  { suffix: "_cont", description: "Contains (case-insensitive)", example: 'title_cont=jazz' },
  { suffix: "_not_cont", description: "Does not contain", example: 'title_not_cont=test' },
  { suffix: "_start", description: "Starts with", example: 'name_start=The' },
  { suffix: "_end", description: "Ends with", example: 'email_end=gmail.com' },
  { suffix: "_gt", description: "Greater than", example: 'price_gt=50' },
  { suffix: "_lt", description: "Less than", example: 'price_lt=100' },
  { suffix: "_gteq", description: "Greater than or equal", example: 'start_time_gteq=2024-01-01' },
  { suffix: "_lteq", description: "Less than or equal", example: 'start_time_lteq=2024-12-31' },
  { suffix: "_in", description: "In list (comma-separated)", example: 'id_in=1,2,3' },
  { suffix: "_not_in", description: "Not in list", example: 'id_not_in=4,5' },
  { suffix: "_true", description: "Boolean is true", example: 'paid_true=1' },
  { suffix: "_false", description: "Boolean is false", example: 'cash_false=1' },
  { suffix: "_null", description: "Is null", example: 'refunded_at_null=1' },
  { suffix: "_not_null", description: "Is not null", example: 'checked_in_at_not_null=1' },
  { suffix: "_present", description: "Is present (not null/empty)", example: 'email_present=1' },
  { suffix: "_blank", description: "Is blank (null or empty)", example: 'phone_number_blank=1' },
];

export function findResource(name: string): ResourceDef | undefined {
  const lower = name.toLowerCase().replace(/[-_\s]/g, "");
  const allResources = [...RESOURCES, ...CONSUMER_RESOURCES];
  return allResources.find((r) => {
    const rLower = r.name.toLowerCase().replace(/[-_\s]/g, "");
    const cmdLower = r.command.toLowerCase().replace(/[-_\s]/g, "");
    return rLower === lower || rLower.startsWith(lower) || cmdLower.includes(lower);
  });
}
